platform :ios, '11.0'
inhibit_all_warnings!

project './HWLDemoForUIButton+hwlBlock/HWLDemoForUIButton+hwlBlock.xcodeproj'

target 'HWLDemoForUIButton+hwlBlock' do
  pod 'UIButton-hwlBlock', '~> 1.0.6', subspecs: ["HWLEventTargetBlock", "HWLForwardBlock"]
#  pod 'UIButton-hwlBlock', :path => '../UIButton-hwlBlock.podspec', :inhibit_warnings => false#, subspecs: ["HWLEventTargetBlock", "HWLForwardBlock"]
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
